trigger:
  branches:
    include:
      - main

pool:
  name: Self-hosted
  demands:
    - agent.name -equals INVESP00011
  maxParallelism: 1

steps:
  # Confirmación inicial de que el agente está funcionando correctamente
  - task: PowerShell@2
    displayName: '✅ Validar agente'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "El agente está ejecutando la tarea correctamente"

  # Configurar .NET Core SDK
  - task: UseDotNet@2
    displayName: ⚙️ Configurar .NET SDK
    inputs:
      packageType: sdk
      version: 8.0.107
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Restaurar dependencias
  - task: DotNetCoreCLI@2
    displayName: '⬇️ Restaurar dependencias (dotnet restore)'
    inputs:
      command: 'restore'
      projects: '**/Users.API/Users.API/Users.API.csproj'

  # Construir la aplicación
  - task: DotNetCoreCLI@2
    displayName: '👷 Construcción (dotnet build)'
    inputs:
      command: 'build'
      projects: '**/Users.API/Users.API/Users.API.csproj'
      arguments: '--no-restore --configuration Release'

  # Publicar la aplicación
  - task: DotNetCoreCLI@2
    displayName: '📦 Publicar aplicación (dotnet publish)'
    inputs:
      command: 'publish'
      publishWebProjects: true
      zipAfterPublish: false
      projects: '**/Users.API/Users.API/Users.API.csproj'
      arguments: '--no-restore --configuration Release --output $(Build.ArtifactStagingDirectory)/wwwroot'

  # Comprimir los archivos publicados manualmente en un ZIP
  - task: ArchiveFiles@2
    displayName: '📦 Comprimir archivos publicados'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/wwwroot'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/Users.API.zip'

  # Publicar los artefactos
  - task: PublishBuildArtifacts@1
    displayName: '🚀 Publicar artefactos (Drop)'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'

  - task: PowerShell@2
    displayName: 'List files in publish directory'
    inputs:
      targetType: 'inline'
      script: |
        Get-ChildItem "$(Build.ArtifactStagingDirectory)" -Recurse